on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: ecr-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to ECR
        uses: ./
        id: publish
        with:
          tag: 'example-docker-lets-play-fifa'
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get the output message
        run: echo "The message was -> ${{ steps.hello.outputs.message }}"