on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: ecr-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish to ECR
        uses: ./
        id: publish
        with:
          image-tag: 'merchant-ui'
      - name: Get the output message
        run: echo "The message was -> ${{ steps.hello.outputs.message }}"